name: info_a1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_carousel_widget: ^3.1.0
  flutter_inappwebview: ^6.1.5
  gap: ^3.0.1
  get: ^4.7.2
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  google_sign_in: ^6.3.0
  http: ^1.4.0
  hugeicons: ^0.0.11
  salomon_bottom_bar: ^3.3.2
  supabase_flutter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
